package models;
// Generated Aug 25, 2012 5:00:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name="classe"
    ,catalog="awmo"
)
public class Classe  implements java.io.Serializable {


     private Long id;
     private Diagrama diagrama;
     private Classe classe;
     private String name;
     private float positionX;
     private float positionY;
     private int textOrder;
     private Set<Tipo> tipos = new HashSet<Tipo>(0);
     private Set<RelacaoClasse> relacaoClassesForSourceClasseId = new HashSet<RelacaoClasse>(0);
     private Set<RelacaoClasse> relacaoClassesForTargetClasseId = new HashSet<RelacaoClasse>(0);
     private Set<Classe> classes = new HashSet<Classe>(0);
     private Set<Operacao> operacaos = new HashSet<Operacao>(0);
     private Set<Atributo> atributos = new HashSet<Atributo>(0);

    public Classe() {
    }

	
    public Classe(Diagrama diagrama, String name, float positionX, float positionY, int textOrder) {
        this.diagrama = diagrama;
        this.name = name;
        this.positionX = positionX;
        this.positionY = positionY;
        this.textOrder = textOrder;
    }
    public Classe(Diagrama diagrama, Classe classe, String name, float positionX, float positionY, int textOrder, Set<Tipo> tipos, Set<RelacaoClasse> relacaoClassesForSourceClasseId, Set<RelacaoClasse> relacaoClassesForTargetClasseId, Set<Classe> classes, Set<Operacao> operacaos, Set<Atributo> atributos) {
       this.diagrama = diagrama;
       this.classe = classe;
       this.name = name;
       this.positionX = positionX;
       this.positionY = positionY;
       this.textOrder = textOrder;
       this.tipos = tipos;
       this.relacaoClassesForSourceClasseId = relacaoClassesForSourceClasseId;
       this.relacaoClassesForTargetClasseId = relacaoClassesForTargetClasseId;
       this.classes = classes;
       this.operacaos = operacaos;
       this.atributos = atributos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="diagrama_id", nullable=false)
    public Diagrama getDiagrama() {
        return this.diagrama;
    }
    
    public void setDiagrama(Diagrama diagrama) {
        this.diagrama = diagrama;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="parent_classe_id")
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }
    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="position_x", nullable=false, precision=12, scale=0)
    public float getPositionX() {
        return this.positionX;
    }
    
    public void setPositionX(float positionX) {
        this.positionX = positionX;
    }
    
    @Column(name="position_y", nullable=false, precision=12, scale=0)
    public float getPositionY() {
        return this.positionY;
    }
    
    public void setPositionY(float positionY) {
        this.positionY = positionY;
    }
    
    @Column(name="text_order", nullable=false)
    public int getTextOrder() {
        return this.textOrder;
    }
    
    public void setTextOrder(int textOrder) {
        this.textOrder = textOrder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="classe")
@OrderBy("id")
    public Set<Tipo> getTipos() {
        return this.tipos;
    }
    
    public void setTipos(Set<Tipo> tipos) {
        this.tipos = tipos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="classeBySourceClasseId")
@OrderBy("id")
    public Set<RelacaoClasse> getRelacaoClassesForSourceClasseId() {
        return this.relacaoClassesForSourceClasseId;
    }
    
    public void setRelacaoClassesForSourceClasseId(Set<RelacaoClasse> relacaoClassesForSourceClasseId) {
        this.relacaoClassesForSourceClasseId = relacaoClassesForSourceClasseId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="classeByTargetClasseId")
@OrderBy("id")
    public Set<RelacaoClasse> getRelacaoClassesForTargetClasseId() {
        return this.relacaoClassesForTargetClasseId;
    }
    
    public void setRelacaoClassesForTargetClasseId(Set<RelacaoClasse> relacaoClassesForTargetClasseId) {
        this.relacaoClassesForTargetClasseId = relacaoClassesForTargetClasseId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="classe")
@OrderBy("id")
    public Set<Classe> getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set<Classe> classes) {
        this.classes = classes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="classe")
@OrderBy("id")
    public Set<Operacao> getOperacaos() {
        return this.operacaos;
    }
    
    public void setOperacaos(Set<Operacao> operacaos) {
        this.operacaos = operacaos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="classe")
@OrderBy("id")
    public Set<Atributo> getAtributos() {
        return this.atributos;
    }
    
    public void setAtributos(Set<Atributo> atributos) {
        this.atributos = atributos;
    }




}


