package models;
// Generated Aug 25, 2012 5:00:02 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name="parametro"
    ,catalog="awmo"
)
public class Parametro  implements java.io.Serializable {


     private Long id;
     private Operacao operacao;
     private Tipo tipo;
     private String name;

    public Parametro() {
    }

    public Parametro(Operacao operacao, Tipo tipo, String name) {
       this.operacao = operacao;
       this.tipo = tipo;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="operacao_id", nullable=false)
    public Operacao getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(Operacao operacao) {
        this.operacao = operacao;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="tipo_id", nullable=false)
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


