package models;
// Generated Aug 25, 2012 5:00:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name="tipo"
    ,catalog="awmo"
)
public class Tipo  implements java.io.Serializable {

    public static final int NATIVE_TYPE = 1;
    public static final int COMPLEX_TYPE = 0;
    

    private Long id;
    private Classe classe;
    private int kind;
    private String nativeTipo;
    private Set<Atributo> atributos = new HashSet<Atributo>(0);
    private Set<Parametro> parametros = new HashSet<Parametro>(0);
    private Set<Operacao> operacaos = new HashSet<Operacao>(0);

    public Tipo() {
    }

	
    public Tipo(int kind) {
        this.kind = kind;
    }
    public Tipo(Classe classe, int kind, String nativeTipo, Set<Atributo> atributos, Set<Parametro> parametros, Set<Operacao> operacaos) {
       this.classe = classe;
       this.kind = kind;
       this.nativeTipo = nativeTipo;
       this.atributos = atributos;
       this.parametros = parametros;
       this.operacaos = operacaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="classe_id")
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }
    
    @Column(name="kind", nullable=false)
    public int getKind() {
        return this.kind;
    }
    
    public void setKind(int kind) {
        this.kind = kind;
    }
    
    @Column(name="native_tipo", length=50)
    public String getNativeTipo() {
        return this.nativeTipo;
    }
    
    public void setNativeTipo(String nativeTipo) {
        this.nativeTipo = nativeTipo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="tipo")
@OrderBy("id")
    public Set<Atributo> getAtributos() {
        return this.atributos;
    }
    
    public void setAtributos(Set<Atributo> atributos) {
        this.atributos = atributos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="tipo")
@OrderBy("id")
    public Set<Parametro> getParametros() {
        return this.parametros;
    }
    
    public void setParametros(Set<Parametro> parametros) {
        this.parametros = parametros;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="tipo")
@OrderBy("id")
    public Set<Operacao> getOperacaos() {
        return this.operacaos;
    }
    
    public void setOperacaos(Set<Operacao> operacaos) {
        this.operacaos = operacaos;
    }




}


